# Generated by Django 4.2.11 on 2024-05-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_in',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('DD', 'ДД'), ('TANK', 'Танк'), ('HEAL', 'Хил'), ('TREADER', 'Торговец'), ('GUILDMASTER', 'Гилдмастер'), ('QUESTGIVER', 'Квестгивер'), ('BLACKSMITH', 'Кузнец'), ('TANNER', 'Кожевник'), ('POTIONEER', 'Зельевар'), ('SPELLMASTER', 'Мастер заклинаний')], default='DD', max_length=11),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='DD', on_delete=django.db.models.deletion.CASCADE, to='Ads.category'),
        ),
        migrations.DeleteModel(
            name='Replay',
        ),
        migrations.AddField(
            model_name='response',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads.post'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
